require 'rbconfig'
# ruby 1.8.7 doesn't define RUBY_ENGINE
ruby_engine = defined?(RUBY_ENGINE) ? RUBY_ENGINE : 'ruby'
ruby_version = RbConfig::CONFIG["ruby_version"]
path = File.expand_path('..', __FILE__)
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/concurrent-ruby-1.0.5/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/i18n-1.0.1/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/minitest-5.11.3/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/thread_safe-0.3.6/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/tzinfo-1.2.5/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/activesupport-5.2.0/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/addressable-2.4.0/lib"
$:.unshift "#{path}/"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/colorator-1.1.0/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/multipart-post-2.0.0/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/faraday-0.15.2/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/extensions/universal-darwin-17/2.3.0/ffi-1.9.25"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/ffi-1.9.25/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/forwardable-extended-2.6.0/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/mini_portile2-2.3.0/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/extensions/universal-darwin-17/2.3.0/nokogiri-1.8.4"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/nokogiri-1.8.4/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/html-pipeline-2.8.3/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/rb-fsevent-0.10.3/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/rb-inotify-0.9.10/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/sass-listen-4.0.0/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/sass-3.5.7/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/jekyll-sass-converter-1.5.2/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/ruby_dep-1.5.0/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/listen-3.1.5/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/jekyll-watch-1.5.1/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/kramdown-1.17.0/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/liquid-3.0.6/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/mercenary-0.3.6/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/pathutil-0.16.1/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/rouge-1.11.1/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/safe_yaml-1.0.4/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/jekyll-3.2.1/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/jekyll-feed-0.7.2/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/sawyer-0.8.1/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/octokit-4.9.0/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/jekyll-gist-1.5.0/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/jekyll-mentions-1.4.0/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/jekyll-sitemap-0.11.0/lib"
